const data = [
	{
		"noDefinitif": 1,
		"kodeKlasifikasi": 92344,
		"indeks": "SOSIALISASI",
		"uraianInformasi": "PESERTA MEMBERIKAN PERTANYAAN",
		"tempatSimpan": "KLATEN",
		"tanggalSimpan": "7/26/1999",
		"hakcipta": "Indonesia",
		"lokasiTempat": "Laci emas",
		"kualitas": "Bagus",
		"ukuran": "Besar",
		"keterangan": "Keterangan yang sangat Berharga",
		"foto": "asdasd.jpg",
		"tipeArsip": "personalFile"
	},
	{
		"noDefinitif": 2,
		"kodeKlasifikasi": 239043,
		"indeks": "PELEBARAN",
		"uraianInformasi": "DUDONG SEDANG MANDI",
		"tempatSimpan": "SURABAYA",
		"tanggalSimpan": "7/26/1995",
		"hakcipta": "Indonesia",
		"lokasiTempat": "Laci emas",
		"kualitas": "Bagus",
		"ukuran": "Besar",
		"keterangan": "Keterangan yang sangat Berharga",
		"foto": "asdasd.jpg",
		"tipeArsip": "personalFile"
	},
	{
		"noDefinitif": 3,
		"kodeKlasifikasi": 333222,
		"indeks": "BUDIDAYA",
		"uraianInformasi": "SUASANA ARAPAT KOORDINASI",
		"tempatSimpan": "DADAP",
		"tanggalSimpan": "8/14/1959",
		"hakcipta": "Indonesia",
		"lokasiTempat": "Laci emas",
		"kualitas": "Bagus",
		"ukuran": "Besar",
		"keterangan": "Keterangan yang sangat Berharga",
		"foto": "asdasd.jpg",
		"tipeArsip": "foto"
	},
	{
		"noDefinitif": 4,
		"kodeKlasifikasi": 34475,
		"indeks": "MAKLUMAN",
		"uraianInformasi": "DAPUR MEMASAK IKAN",
		"tempatSimpan": "KARANG ANYAR",
		"tanggalSimpan": "7/02/1929",
		"hakcipta": "Indonesia",
		"lokasiTempat": "Laci emas",
		"kualitas": "Bagus",
		"ukuran": "Besar",
		"keterangan": "Keterangan yang sangat Berharga",
		"foto": "asdasd.jpg",
		"tipeArsip": "foto"
	},
	{
		"noDefinitif": 5,
		"kodeKlasifikasi": 98789,
		"indeks": "LOKAKARYA",
		"uraianInformasi": "PESERTA MELIHAT MATERI DI LAYAR PROYEKTOR",
		"tempatSimpan": "KUDUS",
		"tanggalSimpan": "7/26/1999",
		"hakcipta": "Indonesia",
		"lokasiTempat": "Laci emas",
		"kualitas": "Bagus",
		"ukuran": "Besar",
		"keterangan": "Keterangan yang sangat Berharga",
		"foto": "asdasd.jpg",
		"tipeArsip": "video"
	},
	{
		"noDefinitif": 6,
		"kodeKlasifikasi": 309452,
		"indeks": "BERBUSANA",
		"uraianInformasi": "KOMPUTER TUA JAMAN DULU",
		"tempatSimpan": "DEPOK",
		"tanggalSimpan": "7/28/1875",
		"hakcipta": "Indonesia",
		"lokasiTempat": "Laci emas",
		"kualitas": "Bagus",
		"ukuran": "Besar",
		"keterangan": "Keterangan yang sangat Berharga",
		"foto": "asdasd.jpg",
		"tipeArsip": "video"
	},
	{
		"noDefinitif": 7,
		"kodeKlasifikasi": 111222,
		"indeks": "PEMBINAAN ORGANISASI",
		"uraianInformasi": "PAK SUTIOSO MENGECEK KANDUNGAN MINERAL",
		"tempatSimpan": "JAWA",
		"tanggalSimpan": "7/26/1999",
		"hakcipta": "Indonesia",
		"lokasiTempat": "Laci emas",
		"kualitas": "Bagus",
		"ukuran": "Besar",
		"keterangan": "Keterangan yang sangat Berharga",
		"foto": "asdasd.jpg",
		"tipeArsip": "suratMasuk"
	},
	{
		"noDefinitif": 8,
		"kodeKlasifikasi": 34034,
		"indeks": "NYANYI DANGDUT",
		"uraianInformasi": "PAK GURU MANDI DI KALI",
		"tempatSimpan": "CILEDUG",
		"tanggalSimpan": "7/19/1876",
		"hakcipta": "Indonesia",
		"lokasiTempat": "Laci emas",
		"kualitas": "Bagus",
		"ukuran": "Besar",
		"keterangan": "Keterangan yang sangat Berharga",
		"foto": "asdasd.jpg",
		"tipeArsip": "suratMasuk"
	},
	{
		"noDefinitif": 9,
		"kodeKlasifikasi": 67523,
		"indeks": "PEMADAM KEBAKARAN ORGANISASI",
		"uraianInformasi": "PAK SUTIOSO SIRAM API",
		"tempatSimpan": "PAPUA",
		"tanggalSimpan": "7/26/1999",
		"hakcipta": "Indonesia",
		"lokasiTempat": "Laci emas",
		"kualitas": "Bagus",
		"ukuran": "Besar",
		"keterangan": "Keterangan yang sangat Berharga",
		"foto": "asdasd.jpg",
		"tipeArsip": "suratKeluar"
	},
	{
		"noDefinitif": 10,
		"kodeKlasifikasi": 292384,
		"indeks": "PENDUKUNG DEMO",
		"uraianInformasi": "MAHASISWA BERTERIAK",
		"tempatSimpan": "KALIMANTAN",
		"tanggalSimpan": "12/01/2012",
		"hakcipta": "Indonesia",
		"lokasiTempat": "Laci emas",
		"kualitas": "Bagus",
		"ukuran": "Besar",
		"keterangan": "Keterangan yang sangat Berharga",
		"foto": "asdasd.jpg",
		"tipeArsip": "suratKeluar"
	},
	{
		"noDefinitif": 11,
		"kodeKlasifikasi": 44213,
		"indeks": "TANAMAN HANGUS",
		"uraianInformasi": "DENGAN TANAMAN BISA KEBAKAR",
		"tempatSimpan": "JAWA",
		"tanggalSimpan": "3/11/1969",
		"hakcipta": "Indonesia",
		"lokasiTempat": "Laci emas",
		"kualitas": "Bagus",
		"ukuran": "Besar",
		"keterangan": "Keterangan yang sangat Berharga",
		"foto": "asdasd.jpg",
		"tipeArsip": "kartoGrafi"
	},
	{
		"noDefinitif": 12,
		"kodeKlasifikasi": 2342,
		"indeks": "SABUN BERACUN",
		"uraianInformasi": "MEYEBABKAN GATAL",
		"tempatSimpan": "SUMATERA",
		"tanggalSimpan": "9/16/2011",
		"hakcipta": "Indonesia",
		"lokasiTempat": "Laci emas",
		"kualitas": "Bagus",
		"ukuran": "Besar",
		"keterangan": "Keterangan yang sangat Berharga",
		"foto": "asdasd.jpg",
		"tipeArsip": "kartoGrafi"
	}
]




export default data;