import Constant from "./constant";

let DynamicData = {};

DynamicData[Constant.SIKAD] = {
  title: "sikad",
  subTitle:
    "Sistem Kearsipan Dinas Lingkungan Hidup Dan Kehutanan Provinsi Jawa Tengah",
  logo: "/images/logo-dinas.png",
  logoWidthNavbar: 50,
  logoWidthLogin: 80,
  tableSearchKey: "uraianInformasi",
  color: {
    mainColor: "#001529",
    mainColorRGBA: "FF001529",
    secondColor: "#000C17",
    thirdColor: "#FFFFFF",
    thirdColorRGBA: "FFFFFFFF",
    pdfColor: {
      main: "#001529",
      second: "#189AD3",
      third: "#FFFFFF",
    },
    chartColor: [
      "#001529",
      "#01264a",
      "#02396f",
      "#0059af",
      "#007cef",
      "#1890ff",
    ],
  },
  menu: [
    {
      title: "Menu Utama",
      pathName: "/sikad/dashboard",
      icon: "bar-chart",
      childMenu: [],
    },
    {
      title: "Arsip",
      pathName: "/sikad/arsip",
      icon: "database",
      childMenu: [
        {
          title: "Personal File",
          pathName: "/sikad/arsip/personal-file",
          icon: "file-text",
          childMenu: [],
        },
        {
          title: "Foto",
          pathName: "/sikad/arsip/foto",
          icon: "picture",
          childMenu: [],
        },
        {
          title: "Video",
          pathName: "/sikad/arsip/video",
          icon: "play-square",
          childMenu: [],
        },
        {
          title: "Surat Masuk",
          pathName: "/sikad/arsip/surat-masuk",
          icon: "file-text",
          childMenu: [],
        },
        {
          title: "Surat Keluar",
          pathName: "/sikad/arsip/surat-keluar",
          icon: "file-text",
          childMenu: [],
        },
        {
          title: "Kartografi",
          pathName: "/sikad/arsip/kartografi",
          icon: "file-text",
          childMenu: [],
        },
      ],
    },
    {
      title: "Tambah Data",
      pathName: "/sikad/tambah-data",
      icon: "file-add",
      childMenu: [],
    },
  ],
  column: [
    {
      title: "No",
      dataIndex: "noDefinitif",
      align: "center",
      sorter: (a, b) => a.noDefinitif - b.noDefinitif,
      width: "5%",
    },
    {
      title: "Kode Klasifikasi",
      dataIndex: "noKlasifikasi",
      align: "center",
      render: (a) =>
        a.toLocaleString("de-DE", {
          minimumFractionDigits: 0,
          maximumFractionDigits: 0,
        }),
      sorter: (a, b) => a.noKlasifikasi - b.noKlasifikasi,
      width: "10%",
    },
    {
      title: "Indeks",
      dataIndex: "indeks",
      align: "center",
      width: "10%",
    },
    {
      title: "Uraian Informasi",
      dataIndex: "uraianInformasi",
      align: "center",
      width: "15%",
    },
    {
      title: "Lokasi",
      dataIndex: "lokasiTempat",
      align: "center",
      width: "7%",
    },
    {
      title: "Tanggal",
      dataIndex: "tanggalSimpan",
      align: "center",
      width: "8%",
    },
  ],
  generateExcelData: (data) => {
    return data.map((e) => ({
      No: e.noDefinitif,
      "Kode Klarifikasi": e.noKlasifikasi,
      Indeks: e.indeks,
      "Hak Cipta": e.hakCipta,
      "Uraian Informasi": e.uraianInformasi,
      Lokasi: e.lokasiTempat,
      "Tempat Simpan": e.tempatSimpan,
      Waktu: e.tanggalSimpan,
      "Ukuran ": `${e.panjangFoto} Cm X ${e.lebarFoto} Cm`,
      Kualitas: e.kualitasFoto ? "Baik" : "Buruk",
      Keterangan: e.keterangan,
    }));
  },
  excelColumn: (colomStyle) => {
    return [
      { title: "No", style: colomStyle, width: { wch: 4 } },
      { title: "Kode Klasifikasi", style: colomStyle, width: { wch: 14 } },
      { title: "Indeks", style: colomStyle, width: { wch: 20 } },
      { title: "Hak Cipta", style: colomStyle, width: { wch: 15 } },
      { title: "Uraian Informasi", style: colomStyle, width: { wch: 50 } },
      { title: "Lokasi", style: colomStyle, width: { wch: 15 } },
      { title: "Tempat Simpan", style: colomStyle, width: { wch: 15 } },
      { title: "Waktu", style: colomStyle, width: { wch: 12 } },
      { title: "Ukuran ", style: colomStyle, width: { wch: 15 } },
      { title: "Kualitas", style: colomStyle, width: { wch: 7 } },
      { title: "Keterangan", style: colomStyle, width: { wch: 50 } },
    ];
  },
};

DynamicData[Constant.SEKDA] = {
  title: "sekda",
  subTitle: "Sistem Kearsipan Dinas Arsip dan Perpustakaan Kota Semarang",
  logo: "/images/semarang.png",
  logoWidthNavbar: 80,
  logoWidthLogin: 120,
  tableSearchKey: "uraianInformasi",
  color: {
    mainColor: "#BBBBBB",
    mainColorRGBA: "FFBBBBBB",
    secondColor: "#AAAAAA",
    thirdColor: "#222222",
    thirdColorRGBA: "FF222222",
    pdfColor: {
      main: "#222222",
      second: "#777777",
      third: "#FFFFFF",
    },
    chartColor: [
      "#3D3D3D",
      "#5C5C5C",
      "#5B5B5B",
      "#787878",
      "#959595",
      "#B1B1B1",
    ],
  },
  menu: [
    {
      title: "Menu Utama",
      pathName: "/sekda/dashboard",
      icon: "bar-chart",
      childMenu: [],
    },
    {
      title: "Arsip",
      pathName: "/sekda/arsip",
      icon: "database",
      childMenu: [
        {
          title: "Arsip Aktif",
          pathName: "/sekda/arsip/arsip-aktif",
          icon: "file-text",
          childMenu: [],
        },
        {
          title: "Arsip Inaktif",
          pathName: "/sekda/arsip/arsip-inaktif",
          icon: "file-text",
          childMenu: [],
        },
        {
          title: "Arsip Statis",
          pathName: "/sekda/arsip/arsip-statis",
          icon: "file-text",
          childMenu: [],
        },
      ],
    },
    {
      title: "Tambah Data",
      pathName: "/sekda/tambah-data",
      icon: "file-add",
      childMenu: [],
    },
  ],
  column: [
    {
      title: "No",
      dataIndex: "noDefinitif",
      align: "center",
      sorter: (a, b) => a.noDefinitif - b.noDefinitif,
      width: "5%",
    },
    {
      title: "Kode Klasifikasi",
      dataIndex: "noKlasifikasi",
      align: "center",
      render: (a) =>
        a.toLocaleString("de-DE", {
          minimumFractionDigits: 0,
          maximumFractionDigits: 0,
        }),
      sorter: (a, b) => a.noKlasifikasi - b.noKlasifikasi,
      width: "10%",
    },
    {
      title: "Indeks",
      dataIndex: "indeks",
      align: "center",
      width: "7%",
    },
    {
      title: "Uraian Informasi",
      dataIndex: "uraianInformasi",
      align: "center",
      width: "20%",
    },
    {
      title: "No Boks",
      dataIndex: "noBoks",
      align: "center",
      width: "5%",
    },
    {
      title: "Tanggal",
      dataIndex: "tanggalArsip",
      align: "center",
      width: "10%",
    },
  ],
  generateExcelData: (data) => {
    return data.map((e) => ({
      No: e.noDefinitif,
      "Kode Klarifikasi": e.noKlasifikasi,
      Indeks: e.indeks,
      "Uraian Informasi": e.uraianInformasi,
      "No Boks": e.noBoks,
      Tanggal: e.tanggalArsip,
    }));
  },
  excelColumn: (colomStyle) => {
    return [
      { title: "No", style: colomStyle, width: { wch: 4 } },
      { title: "Kode Klasifikasi", style: colomStyle, width: { wch: 14 } },
      { title: "Indeks", style: colomStyle, width: { wch: 15 } },
      { title: "Uraian Informasi", style: colomStyle, width: { wch: 50 } },
      { title: "No Boks", style: colomStyle, width: { wch: 10 } },
      { title: "Tanggal", style: colomStyle, width: { wch: 12 } },
    ];
  },
  dataInputObject: [
    {
      title: "No Klasifikasi",
      placeHolder: "Masukkan No Klasifikasi",
      variableName: "noKlasifikasi",
      type: "number",
      maxLength: 5,
      required: true,
      spanSize: 8,
    },
    {
      title: "Tanggal Arsip",
      placeHolder: "Masukkan Tanggal Arsip",
      variableName: "tanggalArsip",
      type: "date",
      maxLength: 15,
      required: true,
      spanSize: 8,
    },
    {
      title: "Tipe Arsip",
      placeHolder: "Pilih Tipe Arsip",
      variableName: "tipeArsip",
      type: "select",
      maxLength: 15,
      required: true,
      spanSize: 8,
      suggestion: [
        {
          value: "arsipAktif",
          label: "Arsip Aktif",
        },
        {
          value: "arsipInaktif",
          label: "Arsip Inaktif",
        },
        {
          value: "arsipStatis",
          label: "Arsip Statis",
        },
      ],
    },
    {
      title: "No Boks",
      placeHolder: "Masukkan No Boks",
      variableName: "noBoks",
      type: "number",
      maxLength: 5,
      required: true,
      spanSize: 12,
    },
    {
      title: "Retensi",
      placeHolder: "Masukkan Retensi",
      variableName: "retensi",
      type: "text",
      maxLength: 5,
      required: true,
      spanSize: 12,
    },
    {
      title: "Keterangan",
      placeHolder: "Masukkan Keterangan",
      variableName: "keterangan",
      type: "text",
      maxLength: 25,
      required: true,
      spanSize: 12,
    },
    {
      title: "Tempat Simpan",
      placeHolder: "Masukkan Tempat Simpan",
      variableName: "tempatSimpan",
      type: "text",
      maxLength: 25,
      required: true,
      spanSize: 12,
    },
    {
      title: "Indeks",
      placeHolder: "Masukkan Indeks",
      variableName: "indeks",
      type: "text",
      maxLength: 25,
      required: true,
      spanSize: 24,
    },
    {
      title: "Uraian Informasi",
      placeHolder: "Masukkan Uraian Informasi",
      variableName: "uraianInformasi",
      type: "textArea",
      maxLength: 100,
      required: true,
      spanSize: 24,
    },
  ],
};

DynamicData[Constant.SIAKUM] = {
  title: "siakum",
  subTitle: "Sistem Arsip Dinas Koperasi dan Usaha Mikro",
  logo: "/images/semarang.png",
  logoWidthNavbar: 70,
  logoWidthLogin: 120,
  tableSearchKey: "noSurat",
  color: {
    mainColor: "#2E856E",
    mainColorRGBA: "FF2E856E",
    secondColor: "#006A4E",
    thirdColor: "#FFFFFF",
    thirdColorRGBA: "FFFFFFFF",
    pdfColor: {
      main: "#2E856E",
      second: "#006A4E",
      third: "#FFFFFF",
    },
    chartColor: [
      "#006A4E",
      "#61B567",
      "#2E856E",
      "#5CA08E",
      "#8ABAAE",
      "#B8D5CD",
    ],
  },
  menu: [
    {
      title: "Menu Utama",
      pathName: "/siakum/dashboard",
      icon: "bar-chart",
      childMenu: [],
    },
    {
      title: "Arsip",
      pathName: "/siakum/arsip",
      icon: "database",
      childMenu: [
        {
          title: "Surat Masuk",
          pathName: "/siakum/arsip/surat-masuk",
          icon: "file-text",
          childMenu: [],
        },
        {
          title: "Surat Keluar",
          pathName: "/siakum/arsip/surat-keluar",
          icon: "file-text",
          childMenu: [],
        },
      ],
    },
    {
      title: "Tambah Data",
      pathName: "/siakum/tambah-data",
      icon: "file-add",
      childMenu: [],
    },
  ],
  column: [
    {
      title: "No Agenda",
      dataIndex: "noAgenda",
      align: "center",
      sorter: (a, b) => a.noAgenda - b.noAgenda,
      width: "7%",
    },
    {
      title: "No Surat",
      dataIndex: "noSurat",
      align: "center",
      width: "10%",
    },
    {
      title: "Tanggal Surat",
      dataIndex: "tanggalSurat",
      align: "center",
      width: "7%",
    },
    {
      title: "Tujuan Surat",
      dataIndex: "tujuanSurat",
      align: "center",
      width: "10%",
    },
    {
      title: "Keterangan / Bidang",
      dataIndex: "keterangan",
      align: "center",
      width: "7%",
    },
    {
      title: "Kode Surat",
      dataIndex: "kodeSurat",
      align: "center",
      width: "5%",
    },
    {
      title: "Perihal",
      dataIndex: "perihal",
      align: "center",
      width: "15%",
    },
    {
      title: "Lokasi Simpan",
      dataIndex: "lokasiSimpan",
      align: "center",
      width: "10%",
    },
  ],
  generateExcelData: (data) => {
    return data.map((e) => ({
      "No Agenda": e.noAgenda,
      "No Surat": e.noSurat,
      "Tanggal Surat": e.tanggalSurat,
      "Tujuan Surat": e.tujuanSurat,
      "Keterangan / Bidang": e.keterangan,
      "Kode Surat": e.kodeSurat,
      Perihal: e.perihal,
      "Tempat Simpan": e.lokasiSimpan,
    }));
  },
  excelColumn: (colomStyle) => {
    return [
      { title: "No Agenda", style: colomStyle, width: { wch: 10 } },
      { title: "No Surat", style: colomStyle, width: { wch: 12 } },
      { title: "Tanggal Surat", style: colomStyle, width: { wch: 12 } },
      { title: "Tujuan Surat", style: colomStyle, width: { wch: 25 } },
      { title: "Keterangan / Bidang", style: colomStyle, width: { wch: 25 } },
      { title: "Kode Surat", style: colomStyle, width: { wch: 12 } },
      { title: "Perihal", style: colomStyle, width: { wch: 30 } },
      { title: "Lokasi Simpan", style: colomStyle, width: { wch: 30 } },
    ];
  },
  dataInputObject: [
    {
      title: "No Agenda",
      placeHolder: "Masukkan No Agenda",
      variableName: "noAgenda",
      type: "number",
      maxLength: 5,
      required: true,
      spanSize: 8,
    },
    {
      title: "Kode Surat",
      placeHolder: "Masukkan Kode Surat",
      variableName: "kodeSurat",
      type: "text",
      maxLength: 5,
      required: true,
      spanSize: 8,
    },
    {
      title: "Tanggal Surat",
      placeHolder: "Masukkan Tanggal Surat",
      variableName: "tanggalSurat",
      type: "date",
      maxLength: 15,
      required: true,
      spanSize: 8,
    },
    {
      title: "Tipe Arsip",
      placeHolder: "Pilih Tipe Arsip",
      variableName: "tipeArsip",
      type: "select",
      maxLength: 15,
      required: true,
      spanSize: 12,
      suggestion: [
        {
          value: "suratMasuk",
          label: "Surat Masuk",
        },
        {
          value: "suratKeluar",
          label: "SuratKeluar",
        },
      ],
    },
    {
      title: "Keterangan / Bidang",
      placeHolder: "Masukkan Keterangan / Bidang",
      variableName: "keterangan",
      type: "text",
      maxLength: 25,
      required: true,
      spanSize: 12,
    },
    {
      title: "No Surat",
      placeHolder: "Masukkan No Surat",
      variableName: "noSurat",
      type: "text",
      maxLength: 50,
      required: true,
      spanSize: 12,
    },
    {
      title: "Lokasi Simpan",
      placeHolder: "Masukkan Lokasi Simpan",
      variableName: "lokasiSimpan",
      type: "text",
      maxLength: 50,
      required: true,
      spanSize: 12,
    },
    {
      title: "Tujuan Surat",
      placeHolder: "Masukkan Tujuan Surat",
      variableName: "tujuanSurat",
      type: "text",
      maxLength: 50,
      required: true,
      spanSize: 24,
    },
    {
      title: "Perihal",
      placeHolder: "Masukkan Perihal",
      variableName: "perihal",
      type: "text",
      maxLength: 100,
      required: true,
      spanSize: 24,
    },
  ],
};

DynamicData[Constant.TAKSI] = {
  title: "taksi",
  subTitle:
    "Temu Balik Arsip Inaktif Dinas Kearsipan dan Perpustakaan Kabupaten Bekasi",
  logo: "/images/bekasi.png",
  logoWidthNavbar: 50,
  logoWidthLogin: 80,
  tableSearchKey: "uraianInformasi",
  color: {
    mainColor: "#2E856E",
    mainColorRGBA: "FF2E856E",
    secondColor: "#006A4E",
    thirdColor: "#FFFFFF",
    thirdColorRGBA: "FFFFFFFF",
    pdfColor: {
      main: "#2E856E",
      second: "#006A4E",
      third: "#FFFFFF",
    },
    chartColor: [
      "#006A4E",
      "#61B567",
      "#2E856E",
      "#5CA08E",
      "#8ABAAE",
      "#B8D5CD",
    ],
  },
  menu: [
    {
      title: "Menu Utama",
      pathName: "/taksi/dashboard",
      icon: "bar-chart",
      childMenu: [],
    },
    {
      title: "Arsip",
      pathName: "/taksi/arsip",
      icon: "database",
      childMenu: [
        {
          title: "Arsip Inaktif",
          pathName: "/taksi/arsip/arsip-inaktif",
          icon: "file-text",
          childMenu: [],
        },
        // {
        //   title: "Surat Keluar",
        //   pathName: "/taksi/arsip/surat-keluar",
        //   icon: "file-text",
        //   childMenu: [],
        // },
      ],
    },
    {
      title: "Kode Klasifikasi",
      pathName: "/taksi/kode-klasifikasi",
      icon: "ordered-list",
      childMenu: [],
    },
    {
      title: "Tambah Data",
      pathName: "/taksi/tambah-data",
      icon: "file-add",
      childMenu: [],
    },
  ],
  column: [
    {
      title: "No",
      dataIndex: "noDefinitif",
      align: "center",
      sorter: (a, b) => a.noDefinitif - b.noDefinitif,
      width: "5%",
    },
    {
      title: "Kode Klasifikasi",
      dataIndex: "kodeKlasifikasi",
      align: "center",
      sorter: (a, b) => a.kodeKlasifikasi - b.kodeKlasifikasi,
      width: "7%",
    },
    {
      title: "Jumlah",
      dataIndex: "jumlah",
      align: "center",
      width: "7%",
    },
    {
      title: "Tingkat Perkembangan",
      dataIndex: "tingkatPerkembangan",
      align: "center",
      width: "10%",
    },
    {
      title: "Indeks",
      dataIndex: "indeks",
      align: "center",
      width: "10%",
    },
    {
      title: "Lokasi Simpan",
      dataIndex: "lokasiSimpan",
      align: "center",
      width: "10%",
    },
    {
      title: "Uraian Informasi",
      dataIndex: "uraianInformasi",
      align: "center",
      width: "15%",
    },
  ],
  column2: [
    {
      title: "Indeks",
      dataIndex: "indeks",
      align: "center",
      width: "20%",
    },
    {
      title: "Kode Klasifikasi",
      dataIndex: "kodeKlasifikasi",
      align: "center",
      sorter: (a, b) => a.kodeKlasifikasi - b.kodeKlasifikasi,
      width: "30%",
    },
  ],
  generateExcelData: (data) => {
    return data.map((e) => ({
      No: e.noDefinitif,
      indeks: e.indeks,
      "Kode Klasifikasi": e.kodeKlasifikasi,
      Jumlah: e.jumlah,
      "Tingkat Perkembangan,": e.tingkatPerkembangan,
      "Lokasi Simpan": e.lokasiSimpan,
      "Uraian Informasi": e.uraianInformasi,
    }));
  },
  excelColumn: (colomStyle) => {
    return [
      { title: "No", style: colomStyle, width: { wch: 5 } },
      { title: "Indeks", style: colomStyle, width: { wch: 10 } },
      { title: "Kode Klasifikasi", style: colomStyle, width: { wch: 15 } },
      { title: "Jumlah", style: colomStyle, width: { wch: 15 } },
      { title: "Tingkat Perkembangan", style: colomStyle, width: { wch: 20 } },
      { title: "Lokasi Simpan", style: colomStyle, width: { wch: 20 } },
      { title: "Uraian Informasi", style: colomStyle, width: { wch: 50 } },
    ];
  },
  dataInputObject: [
    {
      title: "Kode Klasifikasi",
      placeHolder: "Masukkan Kode Klasifikasi",
      variableName: "kodeKlasifikasi",
      type: "number",
      maxLength: 5,
      required: true,
      spanSize: 12,
    },

    {
      title: "Indeks",
      placeHolder: "Masukkan Indeks",
      variableName: "indeks",
      type: "text",
      maxLength: 50,
      required: true,
      spanSize: 12,
    },

    {
      title: "Tingkat Perkembangan",
      placeHolder: "Masukkan Tingkat Perkembangan",
      variableName: "tingkatPerkembangan",
      type: "text",
      maxLength: 15,
      required: true,
      spanSize: 12,
    },
    {
      title: "Jumlah",
      placeHolder: "Masukkan Jumlah",
      variableName: "jumlah",
      type: "text",
      maxLength: 15,
      required: true,
      spanSize: 12,
    },
    {
      title: "Tipe Arsip",
      placeHolder: "Pilih Tipe Arsip",
      variableName: "tipeArsip",
      type: "select",
      maxLength: 20,
      required: true,
      spanSize: 24,
      suggestion: [
        {
          value: "arsipInaktif",
          label: "Arsip Inaktif",
        },
        // {
        //   value: "suratKeluar",
        //   label: "SuratKeluar",
        // },
      ],
    },
    {
      title: "Lokasi Simpan",
      placeHolder: "Masukkan Lokasi Simpan",
      variableName: "lokasiSimpan",
      type: "textArea",
      maxLength: 50,
      required: true,
      spanSize: 24,
    },
    {
      title: "Uraian Informasi",
      placeHolder: "Masukkan Uraian Informasi",
      variableName: "uraianInformasi",
      type: "textArea",
      maxLength: 100,
      required: true,
      spanSize: 24,
    },
  ],
};

export default DynamicData;
